language: node_js
sudo: required
services:
- docker
node_js:
- '8'
before_install:
- "./scripts/setup-db.sh"
after_success: yarn run coverage
deploy:
  provider: npm
  email: nick@cuthbert.co.za
  api_key:
    secure: MMWJLZjrgzICmuZSQQF1G3pHUx8iaD6sJ46aRYciUcz7iyNpmDy7mRTUYwwNNH9l28VcBWRezZm5xlPCMsFiqaWGuqs4Qux4y7EIgYMEy03btfAC0ytmMsOqzuT/U9+NoYOEPYESh31QXjXBglX8KUMXHhY0FGgKuMrI0aoKrZ0bhNGyUp8Ak0CW9SjYncefVZm+ImGP8+x3rnh7VIGVh2TCODG46bt1cBnN/N/e65N+ovql86zJEzlYdI4Su7RXGuVJwiK03q84f77ku4lWPMH5I+qvVQHm96gpih8zUSPNtatauRUgXtPNGANblGWpsCBOtL2I8HccQ9YwEJG589tWORLfhMUstrAruvGF6ys7Bp+WXg91An/UxCtB3ZQtN10qUU4bMaVkS6xjuI8+1AHefMjInnhd6S2VLouJY5KJQIl1B9Kbjuvu9j11YaOfDAtSXsMIh+R5VxIozP3MhqrpI97RKhh+cdmnD/AmDq9VHRKuPmhLAmXLmJhy8YXHh5qY7JNE+scvWPs/MmzHsx/mNbNdnXB7/FQ9+GhZCPqx9uTzscNq50fqL0RRz2FUPnJ0wxpX9cwvmW7dW/3ialyxyXYQJz2tSxrA2Li9Qv5j9Sr55xv+crtQ/hxNSMSmZRALlSQxXqpfxiFzcjA1fsrazXpcJhYekjtKxWTJvB4=
  on:
    tags: true
    repo: ncthbrt/nact-persistence-postgres
    branch: master
    
notifications:
  slack:
    secure: uLOgivlomUhPxRBNEdqnLcFNCag+4xY1ibliDUvH3/h2+MEg2G+sd6FMd1QEpEIUEdzMV+Yhqoxrf9Goeq2hjKi5UbEB3ky9n8Yql6kRTmPeXfvVAMSU1UsQhGDX6IUyENpsywkm0A2QuMP/+3Z7EIXd9cQ4G6iLd3CT+aIXMCz7LY11WaLiwy1zYDoXDA0d6uYgUrUQB3k0TdUQlCC5DqoWJxCAYOawzrKZnrlfrX5VF2P4asLBAWWfEhuawhFVdRoWbE7T58Uw4YB51kG9p6ngtxMM5vLqqoOT+ARQIH/10+Tb/X7D596AuXZt6bBM4LSqaPTXMMlQk7AUTws3dg25wiJbfdPniMzJ8do+6xjf9vz2IE+PYLRU8xraOh5ZG8V2dK4QULpwww2Dbq7DE99kRrAqSMzrkZaklfILRvGSOsAgVrJsYdzuU5DGXGK28QpfGS/8ibcIuo253z+08GEmpgFFaHCH2eG7UiyOkdxjoGPDlkq7fjodhCx0TyS3VnWMrEJNw6+LU47LyFNuQZO9ra7rZdquISJHEnoR092zdS7M/niKvkxCLa22Lrbu4x5vRXW/WV8v28xnqNeFP4Bul6cyo0CefGYpy3LabvHJsJ6Ku6om0skDF7bOGptFvtEH3lWn4A06vqkE5n6UEQ51mHb5ms7ijwUpjd29bc0=
    on_success: change
    on_failure: always
